### ISSUE TITLE
Is there a way to control when to pop events from the bus

### ISSUE THREAD

**Issue by rhythmize** [gelldur/EventBus#31]
I have a use case when I want to pop out the events from the bus manually instead instantaneously.
For instance, notifier will keep pushing events on the bus and they'll be queued. And I'll trigger let's say every 2 seconds and pop those events from the bus and callbacks will be called.

**Comment by gelldur** [comment]
Hello, not sure if it will solve your case but in development branch (more recent version and soon I will push it to master), you can call [EventBus::process](https://github.com/gelldur/EventBus/blob/development/lib/src/dexode/EventBus.hpp#L23) manually.

In new version it is more easy way to manage those things.

**Comment by gelldur** [comment]
Also please check [use case stuff](https://github.com/gelldur/EventBus/tree/development/use_case) or [tests](https://github.com/gelldur/EventBus/tree/development/test/src/dexode/eventbus/test)

If it isn't solving your problem / concept then you can write it down here so in spare time I can prepare "example"

Thanks!

**Comment by rhythmize** [comment]
> Hello, not sure if it will solve your case but in development branch (more recent version and soon I will push it to master), you can call [EventBus::process](https://github.com/gelldur/EventBus/blob/development/lib/src/dexode/EventBus.hpp#L23) manually.

Do I need to pass any extra configuration flags to disable automatic `EventBus::process` call. Because otherwise, the event will already be popped out before I reach the point of manually processing it.

**Comment by gelldur** [comment]
`EventBus::process` isn't called automatically you need call it explicitly.

**Comment by rhythmize** [comment]
I'm sorry if I missed, but then how are event listeners are being called now?

**Comment by gelldur** [comment]
It depends on which version are we talking now :)
- On master: version 2.6.0
Here is no way to "process" it manually you need use AsyncEventBus and call [consume](https://github.com/gelldur/EventBus/blob/master/lib/include/eventbus/AsyncEventBus.h#L187)

You need also use schedule instead notify.

I do **not** recommend using master branch as it is "old" and worse than `development` branch


- On development: version 3.0.0 (stable, I'm using it. Soon will be moved to master)
As I mention previously you can call process manually.

**Comment by rhythmize** [comment]
Oh okay, that sounds good. 
Thanks for clarification.
