### ISSUE TITLE
"General concept" image is not black theme friendly

### ISSUE THREAD

**Issue by YarikTH** [gelldur/EventBus#39]
**Describe the bug**
There is an explanatory image in the main [README.md](https://github.com/gelldur/EventBus/blob/master/README.md).
As a modern guy, I use a dark GitHub theme with a black background. On such a background black lines are invisible and even blocks look out of place. Your image has a transparent background and clearly optimized only for white background. So

**Expected behavior**
"General concept" image looks fine on any background. Maybe via embedding the white background into image itself.

**Comment by gelldur** [comment]
Thanks! I will improve that. You are right. Need to dig and find source :)

**Comment by gelldur** [comment]
I hope now it is ok. Please send screenshot ;) @YarikTH

**Comment by gelldur** [comment]
Not perfect but hey ¯\_(ツ)_/¯

![image](https://user-images.githubusercontent.com/175790/203709135-a0acbcec-e724-4635-bd11-75413d9c8a60.png)

**Comment by YarikTH** [comment]
![image](https://user-images.githubusercontent.com/21075945/203710975-20fe42db-20b2-4d82-8071-b53812b72083.png)
👍
