### ISSUE TITLE
Consider to make a proper GitHub release

### ISSUE THREAD

**Issue by YarikTH** [gelldur/EventBus#40]
**Is your feature request related to a problem? Please describe.**
I use the following code to automatically check for the latest version:
```console
curl --silent "https://api.github.com/repos/gelldur/EventBus/releases/latest" | jq -r .tag_name
```
Unfortunately, it does nothing with git tags, but rather with proper GitHub releases. 

**Describe the solution you'd like**
Make a proper GitHub release for the greater good.

Additionally making a release - allows you to use the automatically updated badge:

[![GitHub Releases](https://img.shields.io/github/release/gelldur/EventBus.svg)](https://github.com/gelldur/EventBus/releases)

```
[![GitHub Releases](https://img.shields.io/github/release/gelldur/EventBus.svg)](https://github.com/gelldur/EventBus/releases)
```

P.S. I'm not a user of a library. Just walked by.

**Comment by gelldur** [comment]
Thank you for the tip. I will improve.

**Comment by gelldur** [comment]
Thank you for pointing that out @YarikTH. Now it should be fixed ;)
![image](https://user-images.githubusercontent.com/175790/123926265-ffc95c00-d98b-11eb-8616-d868c0fa25ac.png)

For reference: https://www.toolsqa.com/git/github-releases/
